apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "preview.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.host | quote }}
spec:
  ingressClassName: {{ .Values.ingressClassName | quote }}
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.host | quote }}
      secretName: {{ include "preview.tlsSecretName" . }}
  {{- end }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  name: http
