{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "preview.postgresSecretName" . }}
  labels:
    {{- include "preview.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ include "preview.postgresPassword" . | quote }}
  DATABASE_URL: {{ include "preview.databaseURL" . | quote }}
{{- end }}
